### ISSUE TITLE
Why this repository?

### ISSUE THREAD

**Issue by Insti** [exercism/mentors#65]
Just a question:

Why are track specific mentoring notes being kept here rather than in the track repositories?

**Comment by iHiD** [comment]
Good question. Four reasons off the top of my head.
1) I wanted to action this immediately. I'd we were to implement this in language repos we would have gone through a cycle of discussion and debate about how they should be structured etc. I wanted to avoid that and just get going. 
2) We have a different set of people maintaining these notes who can merge prs etc. We may add people here who should definitely not have commit bit to a language but should to copy.
3) The plan is to integrate all of these notes into the website. Having one repo to read from and one place I can just arbitrarily make large scale changes to make that possible felt easier. 
4) We will also be adding other types of notes and functionality in here (including scripts) and I didn't want to pollute the language repos with that stuff.

**Comment by Insti** [comment]
:heart: Thanks.
